### ISSUE TITLE
Change in authentication for Netatmo

### ISSUE THREAD

**Issue by djerveren** [psmsmets/thermmode-uiclient#11]
Good morning.

I think this method of authentication is deprecated. When running the `netatmo_access_token` function manually, I get:

```
/usr/bin/curl \
        --silent \
        --show-error \
        --header "accept: application/json" \
        --data grant_type=password \
        --data client_id=$NETATMO_CLIENT_ID \
        --data client_secret=$NETATMO_CLIENT_SECRET \
        --data username=$NETATMO_USERNAME \
        --data password=$NETATMO_PASSWORD \
        --data scope="read_thermostat write_thermostat" \
        https://api.netatmo.com/oauth2/token
       
{"error":"unauthorized_client"}
```

https://dev.netatmo.com/apidocumentation/oauth#authorization-code

**Comment by psmsmets** [comment]
Correct. For a while it is no longer possible to retrieve an access token via password (and the function above). You can create an access token for your own app on <https://dev.netatmo.com/apps/> and set that token in the config file.

I updated the code accordingly.
